# Generated by Django 5.0.1 on 2024-01-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('provider', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
