# Generated by Django 5.0.1 on 2024-01-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_cliente_detalleventa_producto_proveedor_venta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
