# Generated by Django 5.0.1 on 2024-02-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_alter_producto_categoria_alter_producto_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
