# Generated by Django 5.0.1 on 2024-02-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0008_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='http://127.0.0.1:8000/space/media/productos/'),
        ),
    ]
