# Generated by Django 5.0.1 on 2024-02-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0010_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
