# Generated by Django 5.0.1 on 2024-02-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0011_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_prod_proveedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
