# Generated by Django 5.0.1 on 2024-02-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0013_alter_producto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_consumidor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
